### ISSUE TITLE
thêm tính năng tải toàn bộ avatar user của nhóm trên facebook

### ISSUE THREAD

**Issue by phongit1995** [HoangTran0410/FBMediaDownloader#10]
Vui lòng thêm tính năng tải toàn bộ avatar user của nhóm trên facebook

**Comment by HoangTran0410** [comment]
Cảm ơn bạn đã quan tâm tới tool.

Hiện tại mình đang trong quá trình tích hợp FBMediaDownloader vào [Extension Useful-scripts](https://github.com/HoangTran0410/useful-script)

Những bản cập nhật chức năng mới sắp tới sẽ thực hiện ngay trên extension nhé.

Thông tin đến bạn.

**Comment by HoangTran0410** [comment]
Đã có chức năng lấy uid user trên nhóm facebook rồi nhé

![image](https://github.com/HoangTran0410/FBMediaDownloader/assets/36368107/a4c2691e-46f8-432a-81ea-64d336e4f815)
