### ISSUE TITLE
bảng điều khiển cho tôi lỗi này

### ISSUE THREAD

**Issue by Albertaku** [HoangTran0410/FBMediaDownloader#11]
[!] ERROR {
    "error": {
        "message": "Invalid request.",
        "type": "OAuthException",
        "code": 1,
        "fbtrace_id": "AJGrzwyGF0sxlArG_B7hcqF"
    },
    "__fb_trace_id__": "DF9fnAyESul",
    "__www_request_id__": "AJGrzwyGF0sxlArG_B7hcqF"
}
null

**Comment by HoangTran0410** [comment]
your access_token is not valid, or not have permission to download album

please check access_token's permissions here:

https://developers.facebook.com/tools/debug/accesstoken/?access_token=YOUR_ACCESS_TOKEN
