### ISSUE TITLE
Tải story

### ISSUE THREAD

**Issue by NoLoPhe** [HoangTran0410/FBMediaDownloader#2]
Tác giả ơi, có thể thêm chức năng tải story được không? Cám ơn ạ!

**Comment by HoangTran0410** [comment]
Hiện tại mình chưa có chức năng tải story.
Nhưng chức năng mới số 5 (Tải tất cả video được đăng lên bởi người dùng) thì trùng hợp thay nó tải được cả story luôn (story phải đang công khai, ko tải được story đã ẩn).

Nếu có thời gian mình sẽ tìm hiểu cách tải story nhé.

**Comment by NoLoPhe** [comment]
Cám ơn bạn đã trả lời

Vậy là phần mềm của mình có thể tải được cả link story. Mình sẽ thử.
Trước đây mình gặp vấn đề với các tool khác về việc hiển thị link, ví dụ story có nhiều hình ảnh nhưng chỉ hiển thị link của hình ảnh đầu tiên thôi, nên download chỉ được một ảnh đầu tiên.
