### ISSUE TITLE
bug? please fix ..

### ISSUE THREAD

**Issue by risqie95** [HoangTran0410/FBMediaDownloader#3]
![Screenshot (3)](https://user-images.githubusercontent.com/56203366/160262371-bd6e2b5e-0f28-4937-b23e-a9c679517971.png)
this page photo count : 14717 photos

but when i use this script for links, just count 10000 photos link..

![Screenshot (4)](https://user-images.githubusercontent.com/56203366/160262453-5ed27269-9357-4654-8405-d74e1b025654.png)

sorry for my bad english :)
Thanks you

**Comment by HoangTran0410** [comment]
It's so strange. I have no idea for now.

**Comment by HoangTran0410** [comment]
maybe facebook dont want us to download all media only using access_token
I will find solution soon
