### ISSUE TITLE
How to contact with you?

### ISSUE THREAD

**Issue by sesilkam** [HoangTran0410/FBMediaDownloader#4]
I sent you a two mails with questions but nothing... Are you receive my mails?
Really I dont know how to contact with you...

**Comment by sesilkam** [comment]
Can you revive this extension? Or can something like this be done...
https://chrome.google.com/webstore/detail/downalbum/cgjnhhjpfcdhbhlcmmjppicjmgfkppok

**Comment by baamboo** [comment]
Hi!

I received an email with the link. I am testing that tool.



Vào Th 6, 8 thg 4, 2022 vào lúc 16:02 sesilkam ***@***.***>
đã viết:

**Comment by sesilkam** [comment]
I sent two mails to 99.hoangtran@gmail.com with qestions and other links... You receve this mails? Can you confirm on mail?

**Comment by sesilkam** [comment]
Are you read this??? Any reaction???

**Comment by sesilkam** [comment]
Please, can you answer me on mail... Can you make script like extension for Chrome and Edge? I don't understand programming.
Please...

**Comment by HoangTran0410** [comment]
> Please, can you answer me on mail... Can you make script like extension for Chrome and Edge? I don't understand programming. Please...

Sorry for late reply. It hard to transform this tool to extension. Extension is not flexible to download multiple files (photos/videos) at once.
