### ISSUE TITLE
Lỗi xác thực Token

### ISSUE THREAD

**Issue by hungleba** [HoangTran0410/FBMediaDownloader#5]
Hi anh. Em có dùng thử tool để tải images từ album thì gặp lỗi như hình
![image](https://user-images.githubusercontent.com/51266998/168294702-4947249d-d676-48a0-8025-49388ededed1.png)
Em đoán đây là lỗi từ token và đã thử lấy lại token nhiều lần nhưng vẫn không fix được. Liệu có phải code lấy token full quyền bị lỗi?

**Comment by kid1485** [comment]
mình cũng bị như vậy 
![Screenshot 2022-06-18 180905](https://user-images.githubusercontent.com/87401486/174435070-0ff68214-3791-494c-a847-5cdc9d9aa4db.png)

**Comment by HoangTran0410** [comment]
@hungleba fb thường xuyên cập nhật nên các cách lấy token nhiều khi trả về token thiếu quyền. 

Hiện tại bạn dùng bookmark cũ (như bác @kid1485) là được token full quyền nhé.
