### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Ttuan0001** [HoangTran0410/FBMediaDownloader#6]
![image](https://user-images.githubusercontent.com/65747281/175807365-b78d25ba-ca76-48a9-b670-812ba8a9a9a5.png)

**Comment by HoangTran0410** [comment]
Yes. It's a bug.

Fixed:
https://github.com/HoangTran0410/FBMediaDownloader/commit/1b788262e4af850e9a61e2a07e5729b3245dd5de
