### ISSUE TITLE
Hi HoangTran

### ISSUE THREAD

**Issue by johnnyvng** [HoangTran0410/FBMediaDownloader#8]
Thanks for publishing this tool. 

I got this error when trying to download from this page group ID. The token access was retrieved using your bookmark.js file. 

It says
> Chọn chức năng: 1

> Nhập id của đối tượng (user_id/group_id/page_id) (Nhập -1 để quay lại): AnimalMemesss

> Tải bao nhiêu trang (Nhập 0 để tải mọi thứ trên tường): 1

> Có tải cả video không (0-Không, 1-Có): 1

> Tải ảnh chất lượng cao nhất? (0-Không, 1-Có): 1

ĐANG TẢI DỮ LIỆU TRÊN TƯỜNG CỦA AnimalMemesss...

ĐANG TẢI TRANG 1...

[!] ERROR {

    "error": {

        "message": "Invalid request.",

        "type": "OAuthException",

        "code": 1,

        "fbtrace_id": "AxyVQNl6s_FmSD0DXhTSMGF"

    }

}

**Comment by HoangTran0410** [comment]
This error said that your fb-token is not contains full permissions. Please get another fb-token then try again. You can try https://ffb.vn/get-token to get token, WARNING: only use nick-clone to test on that website!
