### ISSUE TITLE
Code 10

### ISSUE THREAD

**Issue by Falcon87262** [HoangTran0410/FBMediaDownloader#9]
Hi.
Tôi đang gặp phải sự cố này khi cố gắng tải xuống phương tiện truyền thông trên tường của trang

`ĐANG TẢI TRANG 1...
> TÌM THẤY 24 file ảnh/video. (TỔNG: 24)
> Đã tạo thư mục downloads/feed_media/goaldigers.
Đang lưu 0: downloads/feed_media/goaldigers/1149560698975543.mp4...
Đang lưu 1: downloads/feed_media/goaldigers/482778866840755.mp4...
Đang lưu 2: downloads/feed_media/goaldigers/756323272103177.mp4...
Đang lưu 3: downloads/feed_media/goaldigers/3176722972594770.mp4...
Đang lưu 4: downloads/feed_media/goaldigers/617756993130352.mp4...
Đang lưu 5: downloads/feed_media/goaldigers/644427080312677.mp4...
Đang lưu 6: downloads/feed_media/goaldigers/472195961245176.mp4...
Đang lưu 7: downloads/feed_media/goaldigers/808319870206697.mp4...
Đang lưu 8: downloads/feed_media/goaldigers/766148574469118.mp4...
Đang lưu 9: downloads/feed_media/goaldigers/5653647291381646.mp4...
Đang lưu 10: downloads/feed_media/goaldigers/361584042853770.mp4...
Đang lưu 11: downloads/feed_media/goaldigers/1725319724512745.mp4...
Đang lưu 12: downloads/feed_media/goaldigers/3362636900634121.mp4...
Đang lưu 13: downloads/feed_media/goaldigers/429821572421765.mp4...
Đang lưu 14: downloads/feed_media/goaldigers/1049705309013023.mp4...
Đang lưu 15: downloads/feed_media/goaldigers/380655570869302.mp4...
Đang lưu 16: downloads/feed_media/goaldigers/759752868684722.mp4...
Đang lưu 17: downloads/feed_media/goaldigers/725493635417466.mp4...
Đang lưu 18: downloads/feed_media/goaldigers/380464657561199.mp4...
Đang lưu 19: downloads/feed_media/goaldigers/774611853984789.mp4...
Đang lưu 20: downloads/feed_media/goaldigers/1417443485399907.mp4...
Đang lưu 21: downloads/feed_media/goaldigers/2086543438174160.mp4...
Đang tìm ảnh có độ phân giải lớn nhất của 380145517554872...
Đang lưu 22: downloads/feed_media/goaldigers/380145517554872.png...
Đang lưu 23: downloads/feed_media/goaldigers/443256347400497.mp4...
ĐANG TẢI TRANG 2...
[!] ERROR {
    "error": {
        "message": "(#10) Application does not have permission for this action",
        "type": "OAuthException",
        "code": 10,
        "fbtrace_id": "A_CeF8BrmGL6qg0wPQbbjc8"
    }
}

=====================================================================
======== FB Media Downloader Tool > Tải ảnh/video trên tường ========
=====================================================================
0: <- Quay lại
1: Tải tất cả ẢNH/VIDEO trên tường của đối tượng (user/gorup/page)
2: Tải tất cả LINK ảnh/video trên tường của đối tượng (user/group/page)

> Chọn chức năng`

Bạn có thể cho tôi biết làm thế nào để giải quyết vấn đề.

**Comment by HoangTran0410** [comment]
this cause by access_token's permission, please check https://github.com/HoangTran0410/FBMediaDownloader/issues/11
